### PR TITLE
Pickle5 backport support for Python3.5

### PR DESCRIPTION
**Pull request by suquark**

### CODE REVIEW

**Comment by suquark** [comment]
The tests have all passed, except 2 issues:

* We got `ValueError: we must use protocol 4 or greater to copy this object; since __getnewargs_ex__ returned keyword arguments.`, which seems to be a 'correct' behavior under python3.5
* Numpy refused to support python3.5, but it can be simply changed by modifying the line checking the python version.

**Comment by robertnishihara** [comment]
Would it make sense to add 3.5 to Travis?

**Comment by pcmoritz** [comment]
@suquark Can you fix the travis tests and add tests for python 3.5 so we can get this merged?

**Comment by suquark** [comment]
The Arm64 errors seem not related.

**Comment by pcmoritz** [comment]
@pitrou Can you take a look at this and see if we can get this merged? It would be great to do that and prepare a new release of pickle5-backport! Let me know if we can help with anything on this front!

@suquark Says the error on ARM is unrelated to this PR and already happens on the current master of this repo (due to a new numpy release that breaks it).

**Comment by pitrou** [comment]
Could you split Python 3.5 support into a separate PR?

**Comment by suquark** [comment]
@pitrou  Sure. Let me make one that only contains the Python3.5 support. BTW, will you also add the bpo-39492 fix (or just sync up with the latest cpython pickle)? This is also critical I think. Otherwise I would also create an another PR to fix the reference count issue.

**Comment by pitrou** [comment]
I think syncing would be best, is that something you want to try to do?

**Comment by suquark** [comment]
Yes, so I will create two PRs, one for the syncing, one for the python3.5 support (based on the synced version)

**Comment by suquark** [comment]
This PR has been divided into #15 and #16.

**Pull request closed without merging**
